# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ModPerl-VersionUtil
version:      0.03
version_from: lib/ModPerl/VersionUtil.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
